language: generic
sudo: required

services:
  - docker

# To run client
before_install:
  - docker build -t sujithnath/react-test -f ./client/Dockerfile.dev ./client

# To run additional scripts from package json
# -- --coverage helps in exiting the test after the test is done
script:
  - docker run -e CI=true sujithnath/react-test npm test -- --coverage

after_success:
  - docker build -t sujithnath/multi-client ./client
  - docker build -t sujithnath/multi-nginx ./nginx
  - docker build -t sujithnath/multi-server ./server
  - docker build -t sujithnath/multi-worker ./worker
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sujithnath/multi-client
  - docker push sujithnath/multi-nginx
  - docker push sujithnath/multi-server
  - docker push sujithnath/multi-worker
