sudo: required
services:
  - docker

before_install:
  - docker build -t sujith/docker-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true sujith/docker-cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-cicd"
  name: "DockerCicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-675106039996"
  bucket_path: "docker-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
